# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usr_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting_Form(object):
    def setupUi(self, Setting_Form):
        Setting_Form.setObjectName("Setting_Form")
        Setting_Form.resize(389, 187)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/computer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Setting_Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Setting_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.id_label = QtWidgets.QLabel(Setting_Form)
        self.id_label.setObjectName("id_label")
        self.horizontalLayout.addWidget(self.id_label)
        self.id_combo = QtWidgets.QComboBox(Setting_Form)
        self.id_combo.setObjectName("id_combo")
        self.horizontalLayout.addWidget(self.id_combo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.user_label = QtWidgets.QLabel(Setting_Form)
        self.user_label.setObjectName("user_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_label)
        self.user_line = QtWidgets.QLineEdit(Setting_Form)
        self.user_line.setObjectName("user_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_line)
        self.password_label = QtWidgets.QLabel(Setting_Form)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_line = QtWidgets.QLineEdit(Setting_Form)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setObjectName("password_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_line)
        self.authority_label = QtWidgets.QLabel(Setting_Form)
        self.authority_label.setObjectName("authority_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.authority_label)
        self.authority_combo = QtWidgets.QComboBox(Setting_Form)
        self.authority_combo.setObjectName("authority_combo")
        self.authority_combo.addItem("")
        self.authority_combo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authority_combo)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(Setting_Form)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.yes_btn = QtWidgets.QPushButton(Setting_Form)
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_2.addWidget(self.yes_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Setting_Form)
        self.cancel_btn.clicked['bool'].connect(Setting_Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Setting_Form)

    def retranslateUi(self, Setting_Form):
        _translate = QtCore.QCoreApplication.translate
        Setting_Form.setWindowTitle(_translate("Setting_Form", "设置"))
        self.id_label.setText(_translate("Setting_Form", "选择用户ID："))
        self.user_label.setText(_translate("Setting_Form", "用户名："))
        self.password_label.setText(_translate("Setting_Form", "密码："))
        self.authority_label.setText(_translate("Setting_Form", "权限："))
        self.authority_combo.setItemText(0, _translate("Setting_Form", "Normal"))
        self.authority_combo.setItemText(1, _translate("Setting_Form", "Administrator"))
        self.cancel_btn.setText(_translate("Setting_Form", "取消"))
        self.yes_btn.setText(_translate("Setting_Form", "确认"))
import resources_rc
